In [3]:
import requests
import pandas as pd
from datetime import datetime
import json

In [4]:
# API base URL
BASE_URL = "http://127.0.0.1:8000"

In [18]:
# Second cell - get today's plants
response = requests.get(f"{BASE_URL}/api/plants/today")
plants = response.json()

In [19]:
# Convert to DataFrame for better visualization
df = pd.DataFrame(plants)
df

,id,name,last_watered,last_fertilized,days_since_watering,days_since_fertilizing,watering_schedule,fertilizing_schedule,needs_water,needs_fertilizer
0,1,Calathea Medalion,2025-05-08,2025-05-08,4,4.0,7,14,False,False
1,2,Calathea Orbifolia,2025-05-12,2025-05-12,0,0.0,7,14,False,False
2,3,Coffea Arabica,2025-05-11,2025-05-06,1,6.0,7,14,False,False
3,4,Epiprenum Aureum,2025-05-08,2025-05-08,4,4.0,7,14,False,False
4,5,Monstera Adenossii,2025-05-11,2025-05-06,1,6.0,7,14,False,False
5,6,Philodendron Hedaracium Brasil,2025-05-05,None,7,NaN,7,14,True,False
6,7,Philodendron Scandens Micans,2025-05-12,2025-05-12,0,0.0,7,14,False,False
7,8,Scindapsus Treubii Moonlight,2025-05-08,2025-05-08,4,4.0,7,14,False,False

In [21]:
word_list = ["listen", "silent", "enlist", "hello", "world", "dog", "god"]

def filter_len_wordlist(word, wordlist):
    filtered_wordlist = []
    for comp_word in wordlist:
        if len(word) == len(comp_word):
            filtered_wordlist.append(comp_word)
    return filtered_wordlist



filter_len_wordlist("lol", word_list)

def find_anagram_pairs(wordlist):

    anagram_tuple_list = []

    for word in wordlist:
        filtered_len_wordlist = filter_len_wordlist(word, wordlist)
        for filtered_word in filtered_len_wordlist:
            matching_letter_count = 0
            for letter in word:
                if letter in filtered_word:
                    matching_letter_count += 1
            if matching_letter_count == len(word):
                anagram_tuple_list.append((word, filtered_word))


    return anagram_tuple_list



 
find_anagram_pairs(word_list)

[('listen', 'listen'),
 ('listen', 'silent'),
 ('listen', 'enlist'),
 ('silent', 'listen'),
 ('silent', 'silent'),
 ('silent', 'enlist'),
 ('enlist', 'listen'),
 ('enlist', 'silent'),
 ('enlist', 'enlist'),
 ('hello', 'hello'),
 ('world', 'world'),
 ('dog', 'dog'),
 ('dog', 'god'),
 ('god', 'dog'),
 ('god', 'god')]